name: test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: 1.2.1
  open_meteo: ^1.0.8
dev_dependencies:
  lints: 4.0.0